const $=s=>document.querySelector(s), app=$('#app');
const KEY='acum-live-v1', bc='BroadcastChannel'in window?new BroadcastChannel('acum-live'):null;
const base={theme:'dark',code:'7291',joined:false,current:1,vote:null,slides:[{type:'title',title:'Viitorul muncii cu AI',subtitle:'Idei reale. Impact real.'},{type:'poll',title:'Care este cea mai mare oportunitate a anului viitor?',options:['Inteligența artificială','Digitalizare','Oameni și competențe','Sustenabilitate'],votes:[42,28,20,10],open:true},{type:'word',title:'Cu ce cuvânt descrii viitorul muncii?',words:{AI:10,adaptare:7,creativitate:6,'învățare':8},open:true},{type:'quiz',title:'Care este primul pas într-o transformare AI responsabilă?',options:['Cumpărăm instrumente','Definim problema','Automatizăm tot','Eliminăm procese'],votes:[3,19,2,1],correct:1,open:true},{type:'qa',title:'Întrebări din public',questions:[['Cum pregătim echipa pentru schimbare?',12],['Ce competențe devin esențiale?',8]],open:true}],presentations:['Viitorul muncii cu AI','Cultura organizațională','Training Leadership']};
let st=Object.assign({},base,JSON.parse(localStorage.getItem(KEY)||'{}'));
function save(){localStorage.setItem(KEY,JSON.stringify(st));bc?.postMessage(st)} bc?.addEventListener('message',e=>{st=e.data;render()}); addEventListener('storage',e=>{if(e.key===KEY){st=JSON.parse(e.newValue);render()}});
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const logo=()=>`<div class="brand"><span class="pulse">∿</span><b>ACUM</b></div>`;
const pct=(a,i)=>Math.round((a[i]||0)/Math.max(1,a.reduce((x,y)=>x+y,0))*100);
const bars=s=>`<div class="bars">${s.options.map((o,i)=>`<div class="bar"><span>${esc(o)}</span><i><em style="width:${pct(s.votes,i)}%"></em></i><b>${pct(s.votes,i)}%</b></div>`).join('')}</div>`;
function nav(active='dashboard'){return `<aside>${logo()}<div class="workspace">Workspace Pro</div>${[['dashboard','Prezentări'],['results','Rezultate'],['settings','Setări']].map(x=>`<button data-go="${x[0]}" class="${active===x[0]?'on':''}">${x[1]}</button>`).join('')}<button data-go="participant">Participant ↗</button></aside>`}
function landing(){return `<header>${logo()}<nav><button data-go="participant">Intră cu un cod</button><button class="primary" data-go="dashboard">Începe gratuit →</button></nav></header><main class="hero"><section><small>PREZENTĂRI CARE PUN OAMENII ÎN MIȘCARE</small><h1>Ideile prind viață.<br><span>ACUM.</span></h1><p>Creează prezentări interactive, implică audiența și obține feedback în timp real prin poll-uri, Word Cloud, quiz și Q&A.</p><div class="actions"><button class="primary" data-go="dashboard">Începe gratuit →</button><button data-go="participant">Intră cu un cod</button></div><div class="chips"><i>Poll-uri live</i><i>Word Cloud</i><i>Quiz</i><i>Q&A</i></div></section><section class="demo"><div class="live">● LIVE · cod 7291</div><h2>${esc(base.slides[1].title)}</h2>${bars(base.slides[1])}</section></main>`}
function dashboard(){return `<div class="shell">${nav()}<main class="page"><div class="head"><div><small>WORKSPACE</small><h2>Prezentările mele</h2><p>Creează, editează și lansează experiențe interactive.</p></div><button class="primary" id="new">＋ Prezentare nouă</button></div><div class="cards">${st.presentations.map((x,i)=>`<article><div class="thumb"><b>${esc(x)}</b>${i===0?'<span>● LIVE</span>':''}</div><div class="cardbody"><h3>${esc(x)}</h3><p>${i===0?'5':'8'} slide-uri · modificat recent</p><button data-go="editor">Editează</button> <button class="violet" data-go="present">▶ Prezintă</button></div></article>`).join('')}<article class="empty" id="new2">＋<br><b>Creează o prezentare nouă</b></article></div></main></div>`}
function editor(){let s=st.slides[st.current];return `<div class="editor"><div class="editorTop"><button data-go="dashboard">←</button><input id="ptitle" value="Viitorul muncii cu AI"><span>● Autosave</span><button data-go="present" class="violet">▶ Lansează</button></div><div class="editorGrid"><section class="slideList">${st.slides.map((x,i)=>`<button data-slide="${i}" class="${i===st.current?'on':''}"><b>${i+1}</b><span>${esc(x.title)}</span></button>`).join('')}<button id="addSlide">＋ Adaugă slide</button></section><section class="canvas">${slideView(s)}</section><section class="props"><small>CONȚINUT</small><h3>${label(s.type)}</h3><div class="types">${['poll','word','quiz','qa'].map(t=>`<button data-type="${t}" class="${s.type===t?'on':''}">${label(t)}</button>`).join('')}</div><label>Titlu / întrebare</label><textarea id="qtitle">${esc(s.title)}</textarea>${(s.type==='poll'||s.type==='quiz')?`<label>Opțiuni</label>${s.options.map((o,i)=>`<input data-opt="${i}" value="${esc(o)}">`).join('')}`:''}<button id="toggle" class="${s.open===false?'danger':''}">${s.open===false?'Deschide votarea':'Închide votarea'}</button></section></div></div>`}
function label(t){return {title:'Titlu',poll:'Poll',word:'Word Cloud',quiz:'Quiz',qa:'Q&A'}[t]}
function slideView(s){if(s.type==='title')return `<small>ACUM LIVE</small><h1>${esc(s.title)}</h1><p>${esc(s.subtitle)}</p>`;if(s.type==='poll'||s.type==='quiz')return `<small>${label(s.type)}</small><h2>${esc(s.title)}</h2>${bars(s)}`;if(s.type==='word')return `<small>WORD CLOUD</small><h2>${esc(s.title)}</h2><div class="cloud">${Object.entries(s.words).sort((a,b)=>b[1]-a[1]).map((w,i)=>`<b style="font-size:${38-i*4}px">${esc(w[0])}</b>`).join('')}</div>`;return `<small>Q&A</small><h2>${esc(s.title)}</h2><div class="questions">${s.questions.map(q=>`<div>▲ ${q[1]} &nbsp; ${esc(q[0])}</div>`).join('')}</div>`}
function present(){let s=st.slides[st.current];return `<main class="present"><div class="presentTop">${logo()}<span>● LIVE &nbsp; 👥 32</span></div><section><div class="big">${slideView(s)}</div><div class="join"><div class="fakeqr">${Array(81).fill(0).map((_,i)=>`<i class="${(i*7+Number(st.code))%5<2?'b':''}"></i>`).join('')}</div><p>Intră pe <b>acum.ro</b></p><h2>${st.code}</h2></div></section><footer><button id="prev">← Anterior</button><button id="toggle">${s.open===false?'Deschide votarea':'Închide votarea'}</button><button id="next">Următor →</button><button data-go="editor">Ieși</button></footer></main>`}
function participant(){let s=st.slides[st.current];return `<main class="phoneBg"><div class="phone"><div class="phoneTop">${logo()}<small>participant</small></div><div class="phoneBody">${!st.joined?`<h2>Bine ai venit!</h2><p>Introdu codul afișat pe ecran.</p><input id="code" value="${st.code}" maxlength="4"><button class="mobilePrimary" id="join">Intră</button>`:participantSlide(s)}</div></div></main>`}
function participantSlide(s){if(s.open===false)return `<div class="closed">🔒 Votarea s-a încheiat. Mulțumim!</div><button id="leave">Ieși</button>`;if(s.type==='poll'||s.type==='quiz')return `<h2>${esc(s.title)}</h2>${s.options.map((o,i)=>`<button class="option ${st.vote===i?'sel':''}" data-vote="${i}">${esc(o)}</button>`).join('')}<button class="mobilePrimary" id="send">Trimite răspunsul</button>`;if(s.type==='word')return `<h2>${esc(s.title)}</h2><input id="word" placeholder="Scrie un cuvânt"><button class="mobilePrimary" id="sendWord">Trimite</button>`;if(s.type==='qa')return `<h2>${esc(s.title)}</h2><textarea id="question" placeholder="Scrie întrebarea ta"></textarea><button class="mobilePrimary" id="sendQ">Trimite întrebarea</button>${s.questions.map((q,i)=>`<button class="option" data-like="${i}">▲ ${q[1]} · ${esc(q[0])}</button>`).join('')}`;return `<h2>${esc(s.title)}</h2><p>${esc(s.subtitle||'Urmărește ecranul principal.')}</p>`}
function results(){let s=st.slides[1];return `<div class="shell">${nav('results')}<main class="page"><div class="head"><div><small>REZULTATE LIVE</small><h2>Viitorul muncii cu AI</h2></div><button>Exportă raport</button></div><div class="metrics">${[['124','Participanți unici'],['87%','Rată de implicare'],[s.votes.reduce((a,b)=>a+b,0),'Răspunsuri'],['4.8/5','Feedback']].map(m=>`<article><b>${m[0]}</b><span>${m[1]}</span></article>`).join('')}</div><article class="resultCard"><h3>${esc(s.title)}</h3>${bars(s)}</article></main></div>`}
function settings(){return `<div class="shell">${nav('settings')}<main class="page"><div class="head"><div><small>WORKSPACE SETTINGS</small><h2>Branding</h2></div></div><article class="settings"><div class="success">✓ Setările au fost salvate</div><label>Numele organizației</label><input value="Organizația mea"><label>Link personalizat</label><input value="acum.ro/organizatia-mea"><label>Culori</label><div><input type="color" value="#31d8ff"> <input type="color" value="#7c5cff"></div><button class="primary">Salvează setările</button></article></main></div>`}
function route(){return location.hash.replace('#/','')||'landing'}
function render(){document.documentElement.dataset.theme=st.theme;app.innerHTML=({landing,dashboard,editor,present,participant,results,settings}[route()]||landing)();bind()}
function go(r){location.hash='#/'+r}
function bind(){document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));document.querySelectorAll('[data-slide]').forEach(b=>b.onclick=()=>{st.current=+b.dataset.slide;save();render()});document.querySelectorAll('[data-type]').forEach(b=>b.onclick=()=>{let s=st.slides[st.current],t=b.dataset.type;s.type=t;s.open=true;if((t==='poll'||t==='quiz')&&!s.options){s.options=['Opțiunea 1','Opțiunea 2'];s.votes=[0,0]}if(t==='word'&&!s.words)s.words={};if(t==='qa'&&!s.questions)s.questions=[];save();render()});$('#qtitle')?.addEventListener('input',e=>{st.slides[st.current].title=e.target.value;save()});document.querySelectorAll('[data-opt]').forEach(i=>i.oninput=e=>{st.slides[st.current].options[+e.target.dataset.opt]=e.target.value;save()});$('#toggle')?.addEventListener('click',()=>{let s=st.slides[st.current];s.open=!s.open;save();render()});$('#prev')?.addEventListener('click',()=>{st.current=Math.max(0,st.current-1);save();render()});$('#next')?.addEventListener('click',()=>{st.current=Math.min(st.slides.length-1,st.current+1);save();render()});$('#join')?.addEventListener('click',()=>{if($('#code').value===st.code){st.joined=true;save();render()}});$('#leave')?.addEventListener('click',()=>{st.joined=false;save();render()});document.querySelectorAll('[data-vote]').forEach(b=>b.onclick=()=>{st.vote=+b.dataset.vote;render()});$('#send')?.addEventListener('click',()=>{let s=st.slides[st.current];if(st.vote!=null&&s.open){s.votes[st.vote]++;st.vote=null;save();render()}});$('#sendWord')?.addEventListener('click',()=>{let v=$('#word').value.trim(),s=st.slides[st.current];if(v){s.words[v]=(s.words[v]||0)+1;save();render()}});$('#sendQ')?.addEventListener('click',()=>{let v=$('#question').value.trim(),s=st.slides[st.current];if(v){s.questions.unshift([v,0]);save();render()}});document.querySelectorAll('[data-like]').forEach(b=>b.onclick=()=>{st.slides[st.current].questions[+b.dataset.like][1]++;save();render()});$('#new')?.addEventListener('click',()=>{st.presentations.push('Prezentare nouă');save();render()});$('#new2')?.addEventListener('click',()=>{st.presentations.push('Prezentare nouă');save();render()});$('#addSlide')?.addEventListener('click',()=>{st.slides.push({type:'poll',title:'Întrebarea ta',options:['Da','Nu'],votes:[0,0],open:true});st.current=st.slides.length-1;save();render()})}
addEventListener('hashchange',render);if(!location.hash)go('landing');else render();
