const $=s=>document.querySelector(s), app=$('#app');
const KEY='acum-live-v2';
const BROKER='wss://broker.hivemq.com:8884/mqtt';
const defaults={theme:'dark',current:1,session:null,sessionActive:false,participants:0,slides:[
 {type:'title',title:'Viitorul muncii cu AI',subtitle:'Idei reale. Impact real.'},
 {type:'poll',title:'Care este cea mai mare oportunitate a anului viitor?',options:['Inteligența artificială','Digitalizare','Oameni și competențe','Sustenabilitate'],votes:[0,0,0,0],open:true},
 {type:'word',title:'Cu ce cuvânt descrii viitorul muncii?',words:{},open:true},
 {type:'quiz',title:'Care este primul pas într-o transformare AI responsabilă?',options:['Cumpărăm instrumente','Definim problema','Automatizăm tot','Eliminăm procese'],votes:[0,0,0,0],correct:1,open:true},
 {type:'qa',title:'Întrebări din public',questions:[],open:true}
],presentations:['Viitorul muncii cu AI','Cultura organizațională','Training Leadership']};
let st=Object.assign({},defaults,JSON.parse(localStorage.getItem(KEY)||'{}'));
let client=null, conn='offline', seen=new Set(), voterId=localStorage.getItem('acum-voter-id')||crypto.randomUUID();
localStorage.setItem('acum-voter-id',voterId);
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const logo=()=>`<div class="brand"><span class="pulse">∿</span><b>ACUM</b></div>`;
const label=t=>({title:'Titlu',poll:'Poll',word:'Word Cloud',quiz:'Quiz',qa:'Q&A'}[t]||t);
const pct=(a,i)=>Math.round((a[i]||0)/Math.max(1,a.reduce((x,y)=>x+y,0))*100);
const bars=s=>`<div class="bars">${s.options.map((o,i)=>`<div class="bar"><span>${esc(o)}</span><i><em style="width:${pct(s.votes,i)}%"></em></i><b>${pct(s.votes,i)}%</b></div>`).join('')}</div>`;
function save(){localStorage.setItem(KEY,JSON.stringify(st))}
function token(){return Array.from(crypto.getRandomValues(new Uint8Array(12)),b=>b.toString(16).padStart(2,'0')).join('')}
function joinToken(){return new URL(location.href).searchParams.get('join')}
function participantUrl(){const u=new URL(location.href);u.hash='';u.search='';u.searchParams.set('join',st.session);return u.toString()}
function topic(kind,session=st.session){return `acum/v2/${session}/${kind}`}
function publicState(){return {session:st.session,current:st.current,slides:st.slides,participants:st.participants,ts:Date.now()}}
function connectHost(){if(!st.session||typeof mqtt==='undefined')return;disconnect();conn='connecting';render();client=mqtt.connect(BROKER,{clientId:'acum-host-'+token().slice(0,12),clean:true,connectTimeout:7000,reconnectPeriod:2500});client.on('connect',()=>{conn='online';client.subscribe(topic('event'));publishState();render()});client.on('reconnect',()=>{conn='reconnecting';render()});client.on('offline',()=>{conn='offline';render()});client.on('error',()=>{conn='offline';render()});client.on('message',(t,p)=>{if(t!==topic('event'))return;try{handleEvent(JSON.parse(p.toString()))}catch{}})}
function connectParticipant(session){if(!session||typeof mqtt==='undefined')return;disconnect();conn='connecting';render();client=mqtt.connect(BROKER,{clientId:'acum-voter-'+voterId.slice(0,12)+'-'+Math.random().toString(36).slice(2,6),clean:true,connectTimeout:7000,reconnectPeriod:2500});client.on('connect',()=>{conn='online';client.subscribe(topic('state',session),()=>sendEvent({type:'presence'},session));render()});client.on('reconnect',()=>{conn='reconnecting';render()});client.on('offline',()=>{conn='offline';render()});client.on('error',()=>{conn='offline';render()});client.on('message',(t,p)=>{if(t!==topic('state',session))return;try{const data=JSON.parse(p.toString());st.session=session;st.current=data.current;st.slides=data.slides;st.participants=data.participants||0;render()}catch{}})}
function disconnect(){try{client?.end(true)}catch{}client=null}
function publishState(){if(client?.connected&&st.session)client.publish(topic('state'),JSON.stringify(publicState()),{qos:0,retain:true})}
function sendEvent(data,session=joinToken()||st.session){if(!client?.connected||!session)return;const ev={...data,id:crypto.randomUUID(),voterId,slide:st.current,ts:Date.now()};client.publish(topic('event',session),JSON.stringify(ev),{qos:0,retain:false})}
function handleEvent(ev){if(!ev?.id||seen.has(ev.id))return;seen.add(ev.id);if(seen.size>1000)seen=new Set([...seen].slice(-500));if(ev.type==='presence'){st.participants=Math.max(st.participants||0,1);save();publishState();render();return}const s=st.slides[ev.slide];if(!s||s.open===false)return;if(ev.type==='vote'&&(s.type==='poll'||s.type==='quiz')&&Number.isInteger(ev.option)&&s.votes[ev.option]!=null)s.votes[ev.option]++;if(ev.type==='word'&&s.type==='word'&&ev.value){const v=String(ev.value).trim().slice(0,40);if(v)s.words[v]=(s.words[v]||0)+1}if(ev.type==='question'&&s.type==='qa'&&ev.value){const q=String(ev.value).trim().slice(0,240);if(q)s.questions.unshift([q,0])}if(ev.type==='like'&&s.type==='qa'&&s.questions[ev.index])s.questions[ev.index][1]++;save();publishState();render()}
function route(){if(joinToken())return'participant';return location.hash.replace('#/','')||'landing'}
function go(r){location.hash='#/'+r}
function status(){return `<span class="status ${conn}">● ${conn==='online'?'conectat':conn==='connecting'?'conectare…':conn==='reconnecting'?'reconectare…':'offline'}</span>`}
function nav(active='dashboard'){return `<aside>${logo()}<div class="workspace">Workspace Pro</div>${[['dashboard','Prezentări'],['results','Rezultate'],['settings','Setări']].map(x=>`<button data-go="${x[0]}" class="${active===x[0]?'on':''}">${x[1]}</button>`).join('')}</aside>`}
function landing(){return `<header>${logo()}<nav><button class="primary" data-go="dashboard">Deschide workspace →</button></nav></header><main class="hero"><section><small>PREZENTĂRI CARE PUN OAMENII ÎN MIȘCARE</small><h1>Ideile prind viață.<br><span>ACUM.</span></h1><p>Creează prezentări interactive, trimite audienței un singur link web și primește voturi live de pe telefon, tabletă sau laptop.</p><div class="actions"><button class="primary" data-go="dashboard">Creează o prezentare →</button></div><div class="chips"><i>Poll-uri live</i><i>Word Cloud</i><i>Quiz</i><i>Q&A</i></div></section><section class="demo"><div class="live">● LIVE · acces prin link web</div><h2>${esc(st.slides[1].title)}</h2>${bars(st.slides[1])}</section></main>`}
function dashboard(){return `<div class="shell">${nav()}<main class="page"><div class="head"><div><small>WORKSPACE</small><h2>Prezentările mele</h2><p>Creează, editează și pornește o sesiune live cu link direct pentru participanți.</p></div><button class="primary" id="new">＋ Prezentare nouă</button></div><div class="cards">${st.presentations.map((x,i)=>`<article><div class="thumb"><b>${esc(x)}</b>${i===0&&st.sessionActive?'<span>● LIVE</span>':''}</div><div class="cardbody"><h3>${esc(x)}</h3><p>${i===0?st.slides.length:8} slide-uri · autosave activ</p><button data-go="editor">Editează</button> <button class="violet" id="launch${i}">▶ Pornește live</button></div></article>`).join('')}<article class="empty" id="new2">＋<br><b>Creează o prezentare nouă</b></article></div></main></div>`}
function editor(){let s=st.slides[st.current];return `<div class="editor"><div class="editorTop"><button data-go="dashboard">←</button><input id="ptitle" value="Viitorul muncii cu AI"><span>● Autosave</span><button id="launchEditor" class="violet">▶ Pornește live</button></div><div class="editorGrid"><section class="slideList">${st.slides.map((x,i)=>`<button data-slide="${i}" class="${i===st.current?'on':''}"><b>${i+1}</b><span>${esc(x.title)}</span></button>`).join('')}<button id="addSlide">＋ Adaugă slide</button></section><section class="canvas">${slideView(s)}</section><section class="props"><small>CONȚINUT</small><h3>${label(s.type)}</h3><div class="types">${['poll','word','quiz','qa'].map(t=>`<button data-type="${t}" class="${s.type===t?'on':''}">${label(t)}</button>`).join('')}</div><label>Titlu / întrebare</label><textarea id="qtitle">${esc(s.title)}</textarea>${(s.type==='poll'||s.type==='quiz')?`<label>Opțiuni</label>${s.options.map((o,i)=>`<input data-opt="${i}" value="${esc(o)}">`).join('')}`:''}<button id="toggle" class="${s.open===false?'danger':''}">${s.open===false?'Deschide votarea':'Închide votarea'}</button></section></div></div>`}
function slideView(s){if(s.type==='title')return `<small>ACUM LIVE</small><h1>${esc(s.title)}</h1><p>${esc(s.subtitle)}</p>`;if(s.type==='poll'||s.type==='quiz')return `<small>${label(s.type)}</small><h2>${esc(s.title)}</h2>${bars(s)}`;if(s.type==='word')return `<small>WORD CLOUD</small><h2>${esc(s.title)}</h2><div class="cloud">${Object.entries(s.words).sort((a,b)=>b[1]-a[1]).map((w,i)=>`<b style="font-size:${Math.max(22,44-i*4)}px">${esc(w[0])}</b>`).join('')||'<p>Răspunsurile vor apărea aici în timp real.</p>'}</div>`;return `<small>Q&A</small><h2>${esc(s.title)}</h2><div class="questions">${s.questions.map(q=>`<div>▲ ${q[1]} &nbsp; ${esc(q[0])}</div>`).join('')||'<p>Întrebările participanților vor apărea aici.</p>'}</div>`}
function present(){let s=st.slides[st.current],url=participantUrl();return `<main class="present"><div class="presentTop">${logo()}<span>${status()} &nbsp; 👥 ${st.participants||0}</span></div><section><div class="big">${slideView(s)}</div><div class="join"><small>PARTICIPĂ LIVE</small><h3>Deschide această adresă web:</h3><div class="shareUrl">${esc(url)}</div><button id="copyLink" class="primary">Copiază linkul</button><p>Nu este necesar cod și nu folosim QR.</p></div></section><footer><button id="prev">← Anterior</button><button id="toggle">${s.open===false?'Deschide votarea':'Închide votarea'}</button><button id="next">Următor →</button><button data-go="editor">Ieși</button></footer></main>`}
function votedMap(){const k='acum-votes-'+(joinToken()||'x');return [k,JSON.parse(localStorage.getItem(k)||'{}')]}
function participant(){let session=joinToken(),s=st.slides[st.current];if(!session)return `<main class="phoneBg"><div class="phone"><div class="phoneTop">${logo()}</div><div class="phoneBody"><div class="closed">Link de participare incomplet. Cere prezentatorului adresa web a sesiunii.</div></div></div></main>`;return `<main class="phoneBg"><div class="phone"><div class="phoneTop">${logo()}${status()}</div><div class="phoneBody">${conn==='online'?participantSlide(s):`<div class="loading"><div class="spinner"></div><h2>Ne conectăm la sesiune…</h2><p>Dacă rețeaua cade, aplicația se va reconecta automat.</p></div>`}</div></div></main>`}
function participantSlide(s){if(!s)return `<div class="loading"><h2>Așteptăm prezentatorul…</h2></div>`;if(s.type==='title')return `<h2>${esc(s.title)}</h2><p>${esc(s.subtitle||'Urmărește ecranul principal.')}</p>`;if(s.open===false)return `<div class="closed">🔒 Votarea pentru acest slide este închisă.</div>`;const [k,m]=votedMap(),done=m[st.current];if((s.type==='poll'||s.type==='quiz')&&done!=null)return `<div class="successVote">✓ Răspuns trimis</div><h2>${esc(s.title)}</h2><p>Ai votat: <b>${esc(s.options[done])}</b></p><p>Rezultatele apar live pe ecranul prezentatorului.</p>`;if(s.type==='poll'||s.type==='quiz')return `<h2>${esc(s.title)}</h2>${s.options.map((o,i)=>`<button class="option" data-vote="${i}">${esc(o)}</button>`).join('')}`;if(s.type==='word')return `<h2>${esc(s.title)}</h2><input id="word" maxlength="40" placeholder="Scrie un cuvânt"><button class="mobilePrimary" id="sendWord">Trimite</button>`;return `<h2>${esc(s.title)}</h2><textarea id="question" maxlength="240" placeholder="Scrie întrebarea ta"></textarea><button class="mobilePrimary" id="sendQ">Trimite întrebarea</button>${s.questions.map((q,i)=>`<button class="option" data-like="${i}">▲ ${q[1]} · ${esc(q[0])}</button>`).join('')}`}
function results(){let s=st.slides[1],total=s.votes.reduce((a,b)=>a+b,0);return `<div class="shell">${nav('results')}<main class="page"><div class="head"><div><small>REZULTATE LIVE</small><h2>Viitorul muncii cu AI</h2></div></div><div class="metrics">${[[st.participants||0,'Participanți conectați'],[total,'Voturi poll'],[Object.values(st.slides[2].words||{}).reduce((a,b)=>a+b,0),'Cuvinte trimise'],[st.slides[4].questions?.length||0,'Întrebări Q&A']].map(m=>`<article><b>${m[0]}</b><span>${m[1]}</span></article>`).join('')}</div><article class="resultCard"><h3>${esc(s.title)}</h3>${bars(s)}</article></main></div>`}
function settings(){return `<div class="shell">${nav('settings')}<main class="page"><div class="head"><div><small>WORKSPACE SETTINGS</small><h2>Branding</h2></div></div><article class="settings"><label>Numele organizației</label><input value="Organizația mea"><label>Culori</label><div><input type="color" value="#31d8ff"> <input type="color" value="#7c5cff"></div><button class="primary">Salvează setările</button></article></main></div>`}
function startLive(){st.session=token();st.sessionActive=true;st.participants=0;st.slides.forEach(s=>{if(s.votes)s.votes=s.votes.map(()=>0);if(s.words)s.words={};if(s.questions)s.questions=[];if('open'in s)s.open=true});save();connectHost();go('present')}
function toast(msg){let el=document.createElement('div');el.className='toast';el.textContent=msg;$('#toast-region')?.appendChild(el);setTimeout(()=>el.remove(),2200)}
function bind(){document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));document.querySelectorAll('[data-slide]').forEach(b=>b.onclick=()=>{st.current=+b.dataset.slide;save();publishState();render()});document.querySelectorAll('[data-type]').forEach(b=>b.onclick=()=>{let s=st.slides[st.current],t=b.dataset.type;s.type=t;s.open=true;if((t==='poll'||t==='quiz')&&!s.options){s.options=['Opțiunea 1','Opțiunea 2'];s.votes=[0,0]}if(t==='word'&&!s.words)s.words={};if(t==='qa'&&!s.questions)s.questions=[];save();publishState();render()});$('#qtitle')?.addEventListener('input',e=>{st.slides[st.current].title=e.target.value;save();publishState()});document.querySelectorAll('[data-opt]').forEach(i=>i.oninput=e=>{st.slides[st.current].options[+e.target.dataset.opt]=e.target.value;save();publishState()});$('#toggle')?.addEventListener('click',()=>{let s=st.slides[st.current];if('open'in s)s.open=!s.open;save();publishState();render()});$('#prev')?.addEventListener('click',()=>{st.current=Math.max(0,st.current-1);save();publishState();render()});$('#next')?.addEventListener('click',()=>{st.current=Math.min(st.slides.length-1,st.current+1);save();publishState();render()});$('#copyLink')?.addEventListener('click',async()=>{try{await navigator.clipboard.writeText(participantUrl());toast('Link copiat!')}catch{prompt('Copiază linkul:',participantUrl())}});document.querySelectorAll('[data-vote]').forEach(b=>b.onclick=()=>{let idx=+b.dataset.vote,[k,m]=votedMap();if(m[st.current]!=null)return;sendEvent({type:'vote',option:idx});m[st.current]=idx;localStorage.setItem(k,JSON.stringify(m));render()});$('#sendWord')?.addEventListener('click',()=>{let v=$('#word').value.trim();if(v){sendEvent({type:'word',value:v});$('#word').value='';toast('Cuvânt trimis')}});$('#sendQ')?.addEventListener('click',()=>{let v=$('#question').value.trim();if(v){sendEvent({type:'question',value:v});$('#question').value='';toast('Întrebare trimisă')}});document.querySelectorAll('[data-like]').forEach(b=>b.onclick=()=>sendEvent({type:'like',index:+b.dataset.like}));$('#new')?.addEventListener('click',()=>{st.presentations.push('Prezentare nouă');save();render()});$('#new2')?.addEventListener('click',()=>{st.presentations.push('Prezentare nouă');save();render()});$('#addSlide')?.addEventListener('click',()=>{st.slides.push({type:'poll',title:'Întrebarea ta',options:['Da','Nu'],votes:[0,0],open:true});st.current=st.slides.length-1;save();render()});$('#launchEditor')?.addEventListener('click',startLive);st.presentations.forEach((_,i)=>$('#launch'+i)?.addEventListener('click',startLive))}
function render(){document.documentElement.dataset.theme=st.theme;app.innerHTML=({landing,dashboard,editor,present,participant,results,settings}[route()]||landing)();bind()}
addEventListener('hashchange',render);
addEventListener('beforeunload',disconnect);
if(joinToken()){location.hash='#/participant';render();connectParticipant(joinToken())}else{if(!location.hash)location.hash='#/landing';render();if(st.sessionActive&&route()==='present')connectHost()}
